class Country:
    def __init__(self, supplier_country_code):
        self.__supplier_country_code = supplier_country_code
        self.__belron_country_code = None
        self.__belron_country_name = None
        self. __load_by_belron_country_code_by_supplier_country_code()

    def __get_supplier_country_code(self):
        return self.__supplier_country_code

    def __set_belron_country_code(self, val):
        self.__belron_country_code = val

    def get_belron_country_code(self):
        return self.__belron_country_code

    def __set_belron_country_name(self, val):
        self.__belron_country_name = val

    def get_belron_country_name(self):
        return self.__belron_country_name

    def __load_by_belron_country_code_by_supplier_country_code(self):
        my_dict = {
            "AD": "AD",
            "AE": "AE",
            "AF": "AF",
            "AG": "AG",
            "AI": "AI",
            "AL": "AL",
            "AM": "AM",
            "AO": "AO",
            "AQ": "AQ",
            "AR": "AR",
            "AS": "AS",
            "AT": "AT",
            "AU": "AU",
            "AW": "AW",
            "AX": "AX",
            "AZ": "AZ",
            "BA": "BA",
            "BB": "BB",
            "BD": "BD",
            "BE": "BE",
            "BF": "BF",
            "BG": "BG",
            "BH": "BH",
            "BI": "BI",
            "BJ": "BJ",
            "BL": "BL",
            "BM": "BM",
            "BN": "BN",
            "BO": "BO",
            "BQ": "BQ",
            "BR": "BR",
            "BS": "BS",
            "BT": "BT",
            "BV": "BV",
            "BW": "BW",
            "BY": "BY",
            "BZ": "BZ",
            "CA": "CA",
            "CC": "CC",
            "CD": "CD",
            "CF": "CF",
            "CG": "CG",
            "CH": "CH",
            "CI": "CI",
            "CK": "CK",
            "CL": "CL",
            "CM": "CM",
            "CN": "CN",
            "CO": "CO",
            "CR": "CR",
            "CU": "CU",
            "CV": "CV",
            "CW": "CW",
            "CX": "CX",
            "CY": "CY",
            "CZ": "CZ",
            "DE": "de",
            "DJ": "DJ",
            "DK": "DK",
            "DM": "DM",
            "DO": "DO",
            "DZ": "DZ",
            "EC": "EC",
            "EE": "EE",
            "EG": "EG",
            "EH": "EH",
            "ER": "ER",
            "ES": "ES",
            "ET": "ET",
            "FI": "FI",
            "FJ": "FJ",
            "FK": "FK",
            "FM": "FM",
            "FO": "FO",
            "FR": "FR",
            "GA": "GA",
            "GB": "GB",
            "GD": "GD",
            "GE": "GE",
            "GF": "GF",
            "GG": "GG",
            "GH": "GH",
            "GI": "GI",
            "GL": "GL",
            "GM": "GM",
            "GN": "GN",
            "GP": "GP",
            "GQ": "GQ",
            "GR": "GR",
            "GS": "GS",
            "GT": "GT",
            "GU": "GU",
            "GW": "GW",
            "GY": "GY",
            "HK": "HK",
            "HM": "HM",
            "HN": "HN",
            "HR": "HR",
            "HT": "HT",
            "HU": "HU",
            "ID": "ID",
            "IE": "IE",
            "IL": "IL",
            "IM": "IM",
            "IN": "IN",
            "IO": "IO",
            "IQ": "IQ",
            "IR": "IR",
            "IS": "IS",
            "IT": "IT",
            "JE": "JE",
            "JM": "JM",
            "JO": "JO",
            "JP": "JP",
            "KE": "KE",
            "KG": "KG",
            "KH": "KH",
            "KI": "KI",
            "KM": "KM",
            "KN": "KN",
            "KP": "KP",
            "KR": "KR",
            "KW": "KW",
            "KY": "KY",
            "KZ": "KZ",
            "LA": "LA",
            "LB": "LB",
            "LC": "LC",
            "LI": "LI",
            "LK": "LK",
            "LR": "LR",
            "LS": "LS",
            "LT": "LT",
            "LU": "LU",
            "LV": "LV",
            "LY": "LY",
            "MA": "MA",
            "MC": "MC",
            "MD": "MD",
            "ME": "ME",
            "MF": "MF",
            "MG": "MG",
            "MH": "MH",
            "MK": "MK",
            "ML": "ML",
            "MM": "MM",
            "MN": "MN",
            "MO": "MO",
            "MP": "MP",
            "MQ": "MQ",
            "MR": "MR",
            "MS": "MS",
            "MT": "MT",
            "MU": "MU",
            "MV": "MV",
            "MW": "MW",
            "MX": "MX",
            "MY": "MY",
            "MZ": "MZ",
            "NA": "NA",
            "NC": "NC",
            "NE": "NE",
            "NF": "NF",
            "NG": "NG",
            "NI": "NI",
            "NL": "NL",
            "NO": "NO",
            "NP": "NP",
            "NR": "NR",
            "NU": "NU",
            "NZ": "NZ",
            "OM": "OM",
            "PA": "PA",
            "PE": "PE",
            "PF": "PF",
            "PG": "PG",
            "PH": "PH",
            "PK": "PK",
            "PL": "PL",
            "PM": "PM",
            "PN": "PN",
            "PR": "PR",
            "PS": "PS",
            "PT": "PT",
            "PW": "PW",
            "PY": "PY",
            "QA": "QA",
            "RE": "RE",
            "RO": "RO",
            "RS": "RS",
            "RU": "RU",
            "RW": "RW",
            "SA": "SA",
            "SB": "SB",
            "SC": "SC",
            "SD": "SD",
            "SE": "SE",
            "SG": "SG",
            "SH": "SH",
            "SI": "SI",
            "SJ": "SJ",
            "SK": "SK",
            "SL": "SL",
            "SM": "SM",
            "SN": "SN",
            "SO": "SO",
            "SR": "SR",
            "SS": "SS",
            "ST": "ST",
            "SV": "SV",
            "SX": "SX",
            "SY": "SY",
            "SZ": "SZ",
            "TC": "TC",
            "TD": "TD",
            "TF": "TF",
            "TG": "TG",
            "TH": "TH",
            "TJ": "TJ",
            "TK": "TK",
            "TL": "TL",
            "TM": "TM",
            "TN": "TN",
            "TO": "TO",
            "TR": "TR",
            "TT": "TT",
            "TV": "TV",
            "TW": "TW",
            "TZ": "TZ",
            "UA": "UA",
            "UG": "UG",
            "UM": "UM",
            "US": "US",
            "UY": "UY",
            "UZ": "UZ",
            "VA": "VA",
            "VC": "VC",
            "VE": "VE",
            "VG": "VG",
            "VI": "VI",
            "VN": "VN",
            "VU": "VU",
            "WF": "WF",
            "WS": "WS",
            "YE": "YE",
            "YT": "YT",
            "ZA": "ZA",
            "ZM": "ZM",
            "ZW": "ZW"
        }
        supplier_country_code = self.__get_supplier_country_code()
        belron_county_code = my_dict.get(supplier_country_code)
        if belron_county_code is None:
            self.__set_belron_country_code("none")
        else:
            self.__set_belron_country_code(belron_county_code)
        self.__load_country_name_by_belron_country_code()

    def __load_country_name_by_belron_country_code(self):
        my_dict = {
            "AD": "Andorra",
            "AE": "United Arab Emirates",
            "AF": "Afghanistan",
            "AG": "Antigua and Barbuda",
            "AI": "Anguilla",
            "AL": "Albania",
            "AM": "Armenia",
            "AO": "Angola",
            "AQ": "Antarctica",
            "AR": "Argentina",
            "AS": "American Samoa",
            "AT": "Austria",
            "AU": "Australia",
            "AW": "Aruba",
            "AX": "Åland Islands",
            "AZ": "Azerbaijan",
            "BA": "Bosnia and Herzegovina",
            "BB": "Barbados",
            "BD": "Bangladesh",
            "BE": "Belgium",
            "BF": "Burkina Faso",
            "BG": "Bulgaria",
            "BH": "Bahrain",
            "BI": "Burundi",
            "BJ": "Benin",
            "BL": "Saint Barthélemy",
            "BM": "Bermuda",
            "BN": "Brunei Darussalam",
            "BO": "Bolivia (Plurinational State of)",
            "BQ": "Bonaire, Sint Eustatius and Saba",
            "BR": "Brazil",
            "BS": "Bahamas",
            "BT": "Bhutan",
            "BV": "Bouvet Island",
            "BW": "Botswana",
            "BY": "Belarus",
            "BZ": "Belize",
            "CA": "Canada",
            "CC": "Cocos (Keeling) Islands",
            "CD": "Congo, Democratic Republic of the",
            "CF": "Central African Republic",
            "CG": "Congo",
            "CH": "Switzerland",
            "CI": "Côte d'Ivoire",
            "CK": "Cook Islands",
            "CL": "Chile",
            "CM": "Cameroon",
            "CN": "China",
            "CO": "Colombia",
            "CR": "Costa Rica",
            "CU": "Cuba",
            "CV": "Cabo Verde",
            "CW": "Curaçao",
            "CX": "Christmas Island",
            "CY": "Cyprus",
            "CZ": "Czechia",
            "DE": "Germany",
            "DJ": "Djibouti",
            "DK": "Denmark",
            "DM": "Dominica",
            "DO": "Dominican Republic",
            "DZ": "Algeria",
            "EC": "Ecuador",
            "EE": "Estonia",
            "EG": "Egypt",
            "EH": "Western Sahara",
            "ER": "Eritrea",
            "ES": "Spain",
            "ET": "Ethiopia",
            "FI": "Finland",
            "FJ": "Fiji",
            "FK": "Falkland Islands (Malvinas)",
            "FM": "Micronesia (Federated States of)",
            "FO": "Faroe Islands",
            "FR": "France",
            "GA": "Gabon",
            "GB": "United Kingdom of Great Britain and Northern Ireland",
            "GD": "Grenada",
            "GE": "Georgia",
            "GF": "French Guiana",
            "GG": "Guernsey",
            "GH": "Ghana",
            "GI": "Gibraltar",
            "GL": "Greenland",
            "GM": "Gambia",
            "GN": "Guinea",
            "GP": "Guadeloupe",
            "GQ": "Equatorial Guinea",
            "GR": "Greece",
            "GS": "South Georgia and the South Sandwich Islands",
            "GT": "Guatemala",
            "GU": "Guam",
            "GW": "Guinea-Bissau",
            "GY": "Guyana",
            "HK": "Hong Kong",
            "HM": "Heard Island and McDonald Islands",
            "HN": "Honduras",
            "HR": "Croatia",
            "HT": "Haiti",
            "HU": "Hungary",
            "ID": "Indonesia",
            "IE": "Ireland",
            "IL": "Israel",
            "IM": "Isle of Man",
            "IN": "India",
            "IO": "British Indian Ocean Territory",
            "IQ": "Iraq",
            "IR": "Iran (Islamic Republic of)",
            "IS": "Iceland",
            "IT": "Italy",
            "JE": "Jersey",
            "JM": "Jamaica",
            "JO": "Jordan",
            "JP": "Japan",
            "KE": "Kenya",
            "KG": "Kyrgyzstan",
            "KH": "Cambodia",
            "KI": "Kiribati",
            "KM": "Comoros",
            "KN": "Saint Kitts and Nevis",
            "KP": "Korea (Democratic People's Republic of)",
            "KR": "Korea, Republic of",
            "KW": "Kuwait",
            "KY": "Cayman Islands",
            "KZ": "Kazakhstan",
            "LA": "Lao People's Democratic Republic",
            "LB": "Lebanon",
            "LC": "Saint Lucia",
            "LI": "Liechtenstein",
            "LK": "Sri Lanka",
            "LR": "Liberia",
            "LS": "Lesotho",
            "LT": "Lithuania",
            "LU": "Luxembourg",
            "LV": "Latvia",
            "LY": "Libya",
            "MA": "Morocco",
            "MC": "Monaco",
            "MD": "Moldova, Republic of",
            "ME": "Montenegro",
            "MF": "Saint Martin (French part)",
            "MG": "Madagascar",
            "MH": "Marshall Islands",
            "MK": "North Macedonia",
            "ML": "Mali",
            "MM": "Myanmar",
            "MN": "Mongolia",
            "MO": "Macao",
            "MP": "Northern Mariana Islands",
            "MQ": "Martinique",
            "MR": "Mauritania",
            "MS": "Montserrat",
            "MT": "Malta",
            "MU": "Mauritius",
            "MV": "Maldives",
            "MW": "Malawi",
            "MX": "Mexico",
            "MY": "Malaysia",
            "MZ": "Mozambique",
            "NA": "Namibia",
            "NC": "New Caledonia",
            "NE": "Niger",
            "NF": "Norfolk Island",
            "NG": "Nigeria",
            "NI": "Nicaragua",
            "NL": "Netherlands",
            "NO": "Norway",
            "NP": "Nepal",
            "NR": "Nauru",
            "NU": "Niue",
            "NZ": "New Zealand",
            "OM": "Oman",
            "PA": "Panama",
            "PE": "Peru",
            "PF": "French Polynesia",
            "PG": "Papua New Guinea",
            "PH": "Philippines",
            "PK": "Pakistan",
            "PL": "Poland",
            "PM": "Saint Pierre and Miquelon",
            "PN": "Pitcairn",
            "PR": "Puerto Rico",
            "PS": "Palestine, State of",
            "PT": "Portugal",
            "PW": "Palau",
            "PY": "Paraguay",
            "QA": "Qatar",
            "RE": "Réunion",
            "RO": "Romania",
            "RS": "Serbia",
            "RU": "Russian Federation",
            "RW": "Rwanda",
            "SA": "Saudi Arabia",
            "SB": "Solomon Islands",
            "SC": "Seychelles",
            "SD": "Sudan",
            "SE": "Sweden",
            "SG": "Singapore",
            "SH": "Saint Helena, Ascension and Tristan da Cunha",
            "SI": "Slovenia",
            "SJ": "Svalbard and Jan Mayen",
            "SK": "Slovakia",
            "SL": "Sierra Leone",
            "SM": "San Marino",
            "SN": "Senegal",
            "SO": "Somalia",
            "SR": "Suriname",
            "SS": "South Sudan",
            "ST": "Sao Tome and Principe",
            "SV": "El Salvador",
            "SX": "Sint Maarten (Dutch part)",
            "SY": "Syrian Arab Republic",
            "SZ": "Eswatini",
            "TC": "Turks and Caicos Islands",
            "TD": "Chad",
            "TF": "French Southern Territories",
            "TG": "Togo",
            "TH": "Thailand",
            "TJ": "Tajikistan",
            "TK": "Tokelau",
            "TL": "Timor-Leste",
            "TM": "Turkmenistan",
            "TN": "Tunisia",
            "TO": "Tonga",
            "TR": "Turkey",
            "TT": "Trinidad and Tobago",
            "TV": "Tuvalu",
            "TW": "Taiwan, Province of China",
            "TZ": "Tanzania, United Republic of",
            "UA": "Ukraine",
            "UG": "Uganda",
            "UM": "United States Minor Outlying Islands",
            "US": "United States of America",
            "UY": "Uruguay",
            "UZ": "Uzbekistan",
            "VA": "Holy See",
            "VC": "Saint Vincent and the Grenadines",
            "VE": "Venezuela (Bolivarian Republic of)",
            "VG": "Virgin Islands (British)",
            "VI": "Virgin Islands (U.S.)",
            "VN": "Viet Nam",
            "VU": "Vanuatu",
            "WF": "Wallis and Futuna",
            "WS": "Samoa",
            "YE": "Yemen",
            "YT": "Mayotte",
            "ZA": "South Africa",
            "ZM": "Zambia",
            "ZW": "Zimbabwe"
        }
        belron_country_code = self.get_belron_country_code()
        belron_county_name = my_dict.get(belron_country_code)
        if belron_county_name is None:
            self.__set_belron_country_name("none")
        else:
            self.__set_belron_country_name(belron_county_name)

